### PR TITLE
Updating MSSQL driver to 4.x along with dependencies

### PR DESCRIPTION
**Pull request by Naturious**

### CODE REVIEW

**Comment by Naturious** [comment]
I think all 4.x are solved with this commit.

**Comment by refractalize** [comment]
Hi @Naturious i've finally fixed and merged this in PR #52. I removed the encrypt=true setting, so you'll have to pass this in as a client, but this is consistent with the mssql documentation. Also added URL connection string support. Thanks for your initiative on this, and I'm sorry it's taken so long! Cheers.

**Comment by refractalize** [comment]
released in v3.8

**Comment by Naturious** [comment]
Thank you very much for taking it into consideration, I'll be including this in my future projects now.

**Pull request merged**
