### PR TITLE
Prevent loading of unused drivers

### PR DESCRIPTION
**Pull request by unlight**

### CODE REVIEW

**Comment by refractalize** [comment]
thanks, looks good. just curious tho, what did you see that made you think this was necessary?

The sworm drivers are all loaded, but their corresponding node drivers are not loaded until they're actually used, like this:

```js
var promisify = require('./promisify');
var optionalRequire = require("./optionalRequire");
var debug = require('debug')('sworm:pg');
var urlUtils = require('url');

module.exports = function() {
  var pg = optionalRequire("pg");
```

**Comment by unlight** [comment]
> what did you see that made you think this was necessary?

I'm using mssql only.
I have no problem with this on my local server where node 5.0

But on production server we have node 0.10, and we run into error
```
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (d:\Dev\project\backend\node_modules\sworm\index.js:6:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> 
```
sworm\index.js:6:20
```
var oracleDriver = require("./oracleDriver");
```
Commenting this line and corresponding line ~ 411 fixed the problem.

So, it is just quick solution.
Unfortunately, I have not enough time to figure out what is wrong with `oracleDriver`.

**Comment by refractalize** [comment]
Ah - yes that does make sense. Looks like we're using a some ES6 features - so of course it'll have trouble on Node 0.10. Although most of the ES6 stuff seems to be in the tests and that oracle driver.

Not to worry though, I'll convert them to their ES5 equivalents and made it all compatible with Node 0.10, including a Travis build for it.

**Comment by refractalize** [comment]
Hi - I've published 2.10 which has compatibility with node 0.10 again with tests in travis. Closing this. Thanks for raising it!

**Pull request closed without merging**
